server:
  port: 9090
spring:
  application:
    name: LostItems_Backend
  datasource:
    url: jdbc:mysql://localhost:3306/lost_items
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  
